config/routes.rb
Helpdesk::Application.routes.draw do
  root to: "tickets#index"
  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @ticket = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(params[:project])
    if @ticket.save

      flash[:notice] = "Ticket has been created."
      redirect_to tickets_path
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/tickets/index.html.erb
<%= link_to "New Ticket", new_ticket_path %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= form_for(@ticket) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <%= f.submit %>
<% end %>

app/views/tickets/show.html.erb
<h2><%= @ticket.name %></h2>